src/AppBundle/Entity/ContentAbout.php
<?php
// src/AppBundle/Entity/ContentAbout.php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use AppBundle\Entity\Utility\Traits\IdMapper,
    AppBundle\Entity\Utility\Traits\TextFormatter;

/**
 * @ORM\Entity
 * @ORM\Table(name="content_about")
 */
class ContentAbout
{
    use IdMapper, TextFormatter;

    /**
    * @ORM\Column(type="string", length=200)
    */
    protected $mainTitle;

    /**
    * @ORM\Column(type="string", length=200)
    */
    protected $subTitleAbout;

    /**
    * @ORM\Column(type="string", length=1000)
    */
    protected $textAbout;

    /**
    * @ORM\Column(type="string", length=1000)
    */
    protected $textSubAbout;

    /**
    * @ORM\Column(type="string", length=1000)
    */
    protected $textAboutFeedback;

    public function __toString()
    {
        return ( $this->mainTitle ) ?: '';
    }

    /**
     * Set mainTitle
     *
     * @param string $mainTitle
     *
     * @return ContentAbout
     */
    public function setMainTitle($mainTitle)
    {
        $this->mainTitle = $mainTitle;

        return $this;
    }

    /**
     * Get mainTitle
     *
     * @return string
     */
    public function getMainTitle()
    {
        return $this->mainTitle;
    }

    /**
     * Set subTitleAbout
     *
     * @param string $subTitleAbout
     *
     * @return ContentAbout
     */
    public function setSubTitleAbout($subTitleAbout)
    {
        $this->subTitleAbout = $subTitleAbout;

        return $this;
    }

    /**
     * Get subTitleAbout
     *
     * @return string
     */
    public function getSubTitleAbout()
    {
        return $this->subTitleAbout;
    }

    /**
     * Set textAbout
     *
     * @param string $textAbout
     *
     * @return ContentAbout
     */
    public function setTextAbout($textAbout)
    {
        $this->textAbout = $textAbout;

        return $this;
    }

    /**
     * Get textAbout
     *
     * @return string
     */
    public function getTextAbout()
    {
        return $this->textAbout;
    }

    public function getTextAboutByNewline()
    {
        return $this->explodeByNewline($this->textAbout);
    }

    /**
     * Set textSubAbout
     *
     * @param string $textSubAbout
     *
     * @return ContentAbout
     */
    public function setTextSubAbout($textSubAbout)
    {
        $this->textSubAbout = $textSubAbout;

        return $this;
    }

    /**
     * Get textSubAbout
     *
     * @return string
     */
    public function getTextSubAbout()
    {
        return $this->textSubAbout;
    }

    public function getTextSubAboutByNewline()
    {
        return $this->explodeByNewline($this->textSubAbout);
    }

    /**
     * Set textAboutFeedback
     *
     * @param string $textAboutFeedback
     *
     * @return ContentAbout
     */
    public function setTextAboutFeedback($textAboutFeedback)
    {
        $this->textAboutFeedback = $textAboutFeedback;

        return $this;
    }

    /**
     * Get textAboutFeedback
     *
     * @return string
     */
    public function getTextAboutFeedback()
    {
        return $this->textAboutFeedback;
    }

    public function getTextAboutFeedbackByNewline()
    {
        return $this->explodeByNewline($this->textAboutFeedback);
    }
}

src/AppBundle/Entity/Work.php
<?php
// src/AppBundle/Entity/Work.php
namespace AppBundle\Entity;

use DateTime;

use Symfony\Component\HttpFoundation\File\File,
    Symfony\Component\Validator\Constraints as Assert;

use Doctrine\ORM\Mapping as ORM;

use Vich\UploaderBundle\Mapping\Annotation as Vich;

use AppBundle\Entity\Utility\Traits\IdMapper,
    AppBundle\Entity\Utility\Traits\TextFormatter;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Entity\Repository\WorkRepository")
 * @ORM\Table(name="work")
 *
 * @Vich\Uploadable
 */
class Work
{
    use IdMapper, TextFormatter;

    const WEB_PATH        = "/uploads/work/images/";
    const WEB_PATH_THUMBS = "/uploads/work/images/thumbs/";

    /**
    * @ORM\ManyToOne(targetEntity="Specialization", inversedBy="works")
    * @ORM\JoinColumn(name="specialization_id", referencedColumnName="id")
    */
    protected $specialization;

    /**
    * @ORM\ManyToOne(targetEntity="Service", inversedBy="works")
    * @ORM\JoinColumn(name="service_id", referencedColumnName="id")
    */
    protected $service;

    /**
    * @ORM\Column(type="string", length=100)
    */
    protected $code;

    /**
    * @ORM\Column(type="string", length=100)
    */
    protected $title;

    /**
    * @ORM\Column(type="text")
    */
    protected $description;

    /**
    * @ORM\Column(type="text", name="point_text")
    */
    protected $pointText;

    /**
    * @ORM\Column(type="text", name="resolve_text")
    */
    protected $resolveText;

    /**
    * @ORM\Column(type="text", name="result_text")
    */
    protected $resultText;

    /**
    * @ORM\Column(type="datetime")
    */
    protected $created;

    /**
     * @Assert\File(
     *     maxSize="5M",
     *     mimeTypes={"image/png", "image/jpeg", "image/pjpeg", "image/gif"}
     * )
     *
     * @Vich\UploadableField(mapping="work_image", fileNameProperty="imageName")
     */
    protected $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     **/
    protected $imageName;

    /**
    * @ORM\Column(type="datetime", nullable=true)
    */
    protected $updated;

    /**
     * To string
     */
    public function __toString()
    {
        return ( $this->title ) ?: "";
    }

    /* Vich uploadable methods */

    public function setImageFile($imageFile = NULL)
    {
        $this->imageFile = $imageFile;

        if( $imageFile instanceof File )
            $this->updated = new DateTime;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getImagePath()
    {
        return ( $this->imageName )
            ? self::WEB_PATH.$this->imageName
            : FALSE;
    }

    public function getImageThumbPath()
    {
        return ( $this->imageName )
            ? self::WEB_PATH_THUMBS.$this->imageName
            : FALSE;
    }

    /* END Vich uploadable methods */

    /**
     * Set code
     *
     * @param string $code
     *
     * @return Work
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Work
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set image
     *
     * @param string $image
     *
     * @return Work
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Work
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set pointText
     *
     * @param string $pointText
     *
     * @return Work
     */
    public function setPointText($pointText)
    {
        $this->pointText = $pointText;

        return $this;
    }

    /**
     * Get pointText
     *
     * @return string
     */
    public function getPointText()
    {
        return $this->pointText;
    }

    public function getPointTextByNewline()
    {
        return $this->explodeByNewline($this->pointText);
    }

    /**
     * Set resolveText
     *
     * @param string $resolveText
     *
     * @return Work
     */
    public function setResolveText($resolveText)
    {
        $this->resolveText = $resolveText;

        return $this;
    }

    /**
     * Get resolveText
     *
     * @return string
     */
    public function getResolveText()
    {
        return $this->resolveText;
    }

    public function getResolveTextByNewline()
    {
        return $this->explodeByNewline($this->resolveText);
    }

    /**
     * Set resultText
     *
     * @param string $resultText
     *
     * @return Work
     */
    public function setResultText($resultText)
    {
        $this->resultText = $resultText;

        return $this;
    }

    /**
     * Get resultText
     *
     * @return string
     */
    public function getResultText()
    {
        return $this->resultText;
    }

    public function getResultTextByNewline()
    {
        return $this->explodeByNewline($this->resultText);
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     *
     * @return Work
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set imageName
     *
     * @param string $imageName
     * @return Work
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * Get imageName
     *
     * @return string
     */
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     *
     * @return Work
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set specialization
     *
     * @param \AppBundle\Entity\Specialization $specialization
     *
     * @return Work
     */
    public function setSpecialization(\AppBundle\Entity\Specialization $specialization = null)
    {
        $this->specialization = $specialization;

        return $this;
    }

    /**
     * Get specialization
     *
     * @return \AppBundle\Entity\Specialization
     */
    public function getSpecialization()
    {
        return $this->specialization;
    }

    /**
     * Set service
     *
     * @param \AppBundle\Entity\Service $service
     *
     * @return Work
     */
    public function setService(\AppBundle\Entity\Service $service = null)
    {
        $this->service = $service;

        return $this;
    }

    /**
     * Get service
     *
     * @return \AppBundle\Entity\Service
     */
    public function getService()
    {
        return $this->service;
    }
}

src/AppBundle/Resources/views/Pages/about.html.twig
{# src/AppBundle/Resources/views/pages/about.html.twig #}
{% extends "AppBundle::layout.html.twig" %}

{% block title %}
    {{ metadata.title }} | {{ 'common.site_title'|trans }}
{% endblock %}

{% block meta %}
    {{ parent() }}
    <meta name="description" content="{{ metadata.description }}">
    <meta name="robots" content="{{ metadata.robots }}">
{% endblock %}

{% block openGraph %}
    <meta property="og:url" content="{{ url('about') }}">
    <meta property="og:type" content="website">
    <meta property="og:title" content="{{ 'common.site_title'|trans }} | {{ metadata.title }}">
    <meta property="og:description" content="{{ metadata.description }}">
    <meta property="og:image" content="{{ absolute_url(asset('bundles/app/images/back_1.jpg')) }}">
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/app/css/about.bundle.min.css') }}">
{% endblock %}

{% block content %}
    <main id="content">
        <section class="outer block-holder top">
            <div class="headline">
                <h1>{{ content.about.mainTitle }}</h1>
            </div>
            <div class="inner block top">
                <h2>{{ content.about.subTitleAbout }}</h2>
                <div class="sptr-small">
                    <span class="line"></span>
                    <span class="line"></span>
                </div>

                {% for paragraph in content.about.textAboutByNewline %}
                    <p>{{ paragraph }}</p>
                {% endfor %}

            </div>
        </section>
        <section class="inner middle-holder">
           <div class="logo-white">
               <img src="{{ asset('bundles/app/images/logo-white.png') }}">
           </div>
           <div class="middle-info">

               {% for paragraph in content.about.textSubAboutByNewline %}
                   <p>{{ paragraph }}</p>
               {% endfor %}

           </div>
        </section>
        <section class="outer block-holder bottom">
            <div class="inner block bottom">
                <h2>{{ content.feedback.mainTitle }}</h2>
                <div class="sptr-small">
                    <span class="line"></span>
                    <span class="line"></span>
                </div>

                    {% for paragraph in content.about.textAboutFeedbackByNewline %}
                        <p>{{ paragraph }}</p>
                    {% endfor %}

                <div class="btn-small">
                    <a href="{{ path('feedback') }}">
                        <span>{{ 'button.feedback'|trans }}</span>
                    </a>
                </div>
            </div>
        </section>
        <div class="footer-holder">
            {% include 'AppBundle:Common:footer.html.twig' %}
        </div>
    </main>
{% endblock %}

{% block footer %}{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bundles/app/js/about.bundle.min.js') }}"></script>
{% endblock %}

src/AppBundle/Resources/views/Pages/case-item.html.twig
{# src/AppBundle/Resources/views/pages/case-item.html.twig #}
{% extends "AppBundle::layout.html.twig" %}

{% block title %}
    {{ work.title }} | {{ 'common.site_title'|trans }}
{% endblock %}

{% block meta %}
    {{ parent() }}
    <meta name="description" content="{{ work.description }}">
    <meta name="robots" content="{{ metadata.robots }}">
{% endblock %}

{% block openGraph %}
    <meta property="og:url" content="{{ url('cases_item', { 'id': work.id }) }}">
    <meta property="og:type" content="article">
    <meta property="og:title" content="{{ work.title }} | {{ 'common.site_title'|trans }}">
    <meta property="og:description" content="{{ work.description }}">
    <meta property="og:image" content="{{ absolute_url(vich_uploader_asset(work, 'imageFile')) }}">
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/app/css/case.bundle.min.css') }}">
{% endblock %}

{% block content %}
    <main id="content">
        <article class="case-holder">

            <div class="photo-holder">
                <figure>
                    {% set originalImage = vich_uploader_asset(work, 'imageFile') %}
                    {% set landscapeImage = ( originalImage ) ? originalImage|imagine_filter('case_landscape') : null  %}

                    <div class="background" style="background: url('{{ landscapeImage }}') no-repeat 50% 0; background-size: cover;"></div>
                </figure>
            </div>
            <div class="title-holder">
                <span class="case-number">{{ work.code }}</span>
                <h1>{{ work.title }}</h1>
                <div class="icon-holder">
                    <div class="partners">
                        <span class="icon {{ work.service.icon }}"></span>
                        <p>{{ work.service.title }}</p>
                    </div>
                    <div class="type">
                        <span class="icon {{ work.specialization.icon }}"></span>
                        <p>{{ work.specialization.title }}</p>
                    </div>
                </div>
            </div>
            <time datetime="{{ work.created|date('d/m/Y') }}">{{ work.created|date('d/m/Y') }}</time>
            <div class="inner">
                <div class="info-holder">
                    <h2>{{ 'caseItem.title.pointText'|trans }}</h2>
                    <div class="sptr-small">
                        <span class="line"></span>
                        <span class="line"></span>
                    </div>

                    {% for paragraph in work.pointTextByNewline %}
                        <p>{{ paragraph }}</p>
                    {% endfor %}

                </div>
                <div class="info-holder">
                    <h2>{{ 'caseItem.title.resolveText'|trans }}</h2>
                    <div class="sptr-small">
                        <span class="line"></span>
                        <span class="line"></span>
                    </div>

                    {% for paragraph in work.resolveTextByNewline %}
                        <p>{{ paragraph }}</p>
                    {% endfor %}

                </div>
                <div class="info-holder">
                    <h2>{{ 'caseItem.title.resultText'|trans }}</h2>
                    <div class="sptr-small">
                        <span class="line"></span>
                        <span class="line"></span>
                    </div>

                    {% for paragraph in work.resultTextByNewline %}
                        <p>{{ paragraph }}</p>
                    {% endfor %}

                </div>
            </div>

        </article>

        <div class="arrow-holder">
            {% if closestWorks.prev %}
                <a href="{{ path('cases_item', { 'id': closestWorks.prev }) }}" class="left">
                    <span class="icon-arrow-right"></span>{{ 'caseItem.arrows.previous'|trans }}
                </a>
            {% endif %}
            {% if closestWorks.next %}
                <a href="{{ path('cases_item', { 'id': closestWorks.next }) }}" class="right">
                    {{ 'caseItem.arrows.next'|trans }}<span class="icon-arrow-left"></span>
                </a>
            {% endif %}
        </div>

    </main>

{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bundles/app/js/case.bundle.min.js') }}"></script>
{% endblock %}

src/AppBundle/Resources/views/Pages/cases.html.twig
{# src/AppBundle/Resources/views/pages/cases.html.twig #}
{% extends 'AppBundle::layout.html.twig' %}

{% block title %}
    {{ metadata.title }} | {{ 'common.site_title'|trans }}
{% endblock %}

{% block meta %}
    {{ parent() }}
    <meta name="description" content="{{ metadata.description }}">
    <meta name="robots" content="{{ metadata.robots }}">
{% endblock %}

{% block openGraph %}
    <meta property="og:url" content="{{ url('cases') }}">
    <meta property="og:type" content="website">
    <meta property="og:title" content="{{ 'common.site_title'|trans }} | {{ metadata.title }}">
    <meta property="og:description" content="{{ metadata.description }}">
    <meta property="og:image" content="{{ absolute_url(asset('bundles/app/images/back_1.jpg')) }}">
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/app/css/cases.bundle.min.css') }}">
{% endblock %}

{% block content %}
    <main id="content">
        <section class="inner cases-info">
            <h1>{{ contentWork.mainTitle }}</h1>
            <h2>{{ contentWork.subTitleWork }}</h2>
            <div class="cases">
                {% include 'AppBundle:Common:case.html.twig' with {'works': works} only %}
            </div>
        </section>
    </main>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bundles/app/js/cases.bundle.min.js') }}"></script>
{% endblock %}

src/AppBundle/Resources/views/Pages/feedback.html.twig
{# src/AppBundle/Resources/views/pages/feedback.html.twig #}
{% extends "AppBundle::layout.html.twig" %}

{% block title %}
    {{ metadata.title }} | {{ 'common.site_title'|trans }}
{% endblock %}

{% block meta %}
    {{ parent() }}
    <meta name="description" content="{{ metadata.description }}">
    <meta name="robots" content="{{ metadata.robots }}">
{% endblock %}

{% block openGraph %}
    <meta property="og:url" content="{{ url('feedback') }}">
    <meta property="og:type" content="website">
    <meta property="og:title" content="{{ 'common.site_title'|trans }} | {{ metadata.title }}">
    <meta property="og:description" content="{{ metadata.description }}">
    <meta property="og:image" content="{{ absolute_url(asset('bundles/app/images/back_1.jpg')) }}">
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/app/css/feedback.bundle.min.css') }}">
{% endblock %}

{% block content %}
    <main id="content">
        <section class="outer contacts">
            <h2>{{ contentFeedback.subTitleFeedback }}</h2>
            <div class="sptr-small">
                <span class="line"></span>
                <span class="line"></span>
            </div>
            <ul class="contact-icons">
                <li>
                    <span class="icon icon-email"></span>
                    <a href="mailto:{{ contact.email }}">
                        {{ contact.email }}
                    </a>
                </li>
                <li>
                    <span class="icon icon-phone"></span>
                    <a href="tel:{{ contact.phone|replace({ '(': '', ')': '', '-': '', ' ': '' }) }}">
                        {{ contact.phone }}
                    </a>
                </li>
            </ul>
        </section>
        <section class="outer feedback">
            <h2>{{ contentFeedback.mainTitle }}</h2>
            <div class="sptr-small">
                <span class="line"></span>
                <span class="line"></span>
            </div>

            {% include 'AppBundle:Forms:feedback.html.twig' with {'feedbackView': feedbackView} only %}

        </section>
        <div class="footer-holder">
            {% include 'AppBundle:Common:footer.html.twig' %}
        </div>
    </main>
{% endblock %}

{% block footer %}{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bundles/app/js/feedback.bundle.min.js') }}"></script>
{% endblock %}

src/AppBundle/Resources/views/Pages/index.html.twig
{# src/AppBundle/Resources/views/pages/index.html.twig #}
{% extends 'AppBundle::layout.html.twig' %}

{% block title %}
    {{ 'common.site_title'|trans }} | {{ metadata.title }}
{% endblock %}

{% block meta %}
    {{ parent() }}
    <meta name="description" content="{{ metadata.description }}">
    <meta name="robots" content="{{ metadata.robots }}">
{% endblock %}

{% block openGraph %}
    <meta property="og:url" content="{{ url('home') }}">
    <meta property="og:type" content="website">
    <meta property="og:title" content="{{ 'common.site_title'|trans }}">
    <meta property="og:description" content="{{ metadata.description }}">
    <meta property="og:image" content="{{ absolute_url(asset('bundles/app/images/back_1.jpg')) }}">
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/app/css/home.bundle.min.css') }}">
{% endblock %}

{% block header %}{% endblock %}

{% block menu %}{% endblock %}

{% block content %}
    <header id="header">

    </header>

    {% include 'AppBundle:Common:menu.html.twig' %}

    <main id="content" class="page-row page-row-expanded">
        <div class="outer intro-holder">
            <div class="logo">
                <img src="{{ asset('bundles/app/images/logo.png') }}">
            </div>
            <section class="inner intro-info">
                <div class="intro">
                    <span>{{ content.main.mainTitle }}</span>
                    <h1>{{ content.main.subTitle }}</h1>
                    <p>{{ content.main.textMain }}</p>
                    <div class="btn-large">
                        <a href="{{ path('feedback') }}">
                            <span>{{ 'button.feedback'|trans }}</span>
                        </a>
                    </div>
                </div>
                <div class="scroll-down">
                    <span class="scroll"></span>
                </div>
            </section>
            <section class="inner benefits-holder">
                <div class="benefits">
                    <ul>

                        {% for number in numbers %}
                            <li>
                                <span class="rhombus" data-number="{{ number.number }}"></span>
                                <p>{{ number.title }}</p>
                            </li>
                        {% endfor %}

                    </ul>
                </div>
            </section>
        </div>
        <section class="inner services-holder">
            <div class="logo"><img src="{{ asset('bundles/app/images/logo.png') }}"></div>
            <div class="services">
               <h2>{{ content.service.mainTitle }}</h2>
               <ul class="icons-holder">

                   {% for specialization in specializations %}
                       <li>
                           <span class="icon {{ specialization.icon }}"></span>
                           <div class="sptr-small">
                               <span class="line"></span>
                               <span class="line"></span>
                           </div>
                           <p>{{ specialization.title }}</p>
                       </li>
                   {% endfor %}

               </ul>
               <div class="btn-small">
                    <a href="{{ path('services') }}">
                        <span>{{ 'button.view'|trans }}</span>
                    </a>
                </div>
            </div>
        </section>

        {% if works %}
            <section class="inner cases-holder">
                <h2>{{ content.work.subTitleWork }}</h2>
                <div class="sptr-large">
                    <span class="line"></span>
                    <span class="line"></span>
                </div>

                <div class="cases">

                    {% include 'AppBundle:Common:case.html.twig' with {'works': works} only %}

                </div>
                <div class="btn-small">
                    <a href="{{ path('cases') }}">
                        <span>{{ 'button.view'|trans }}</span>
                    </a>
                </div>
            </section>
        {% endif %}

        <div id="footer-holder">

            {% include 'AppBundle:Common:prefooter.html.twig' %}
            {% include 'AppBundle:Common:footer.html.twig' %}

        </div>
    </main>
{% endblock %}

{% block footer %}{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

src/AppBundle/Resources/views/Pages/services.html.twig
{# src/AppBundle/Resources/views/pages/services.html.twig #}
{% extends 'AppBundle::layout.html.twig' %}

{% block title %}
    {{ metadata.title }} | {{ 'common.site_title'|trans }}
{% endblock %}

{% block meta %}
    {{ parent() }}
    <meta name="description" content="{{ metadata.description }}">
    <meta name="robots" content="{{ metadata.robots }}">
{% endblock %}

{% block openGraph %}
    <meta property="og:url" content="{{ url('services') }}">
    <meta property="og:type" content="website">
    <meta property="og:title" content="{{ 'common.site_title'|trans }} | {{ metadata.title }}">
    <meta property="og:description" content="{{ metadata.description }}">
    <meta property="og:image" content="{{ absolute_url(asset('bundles/app/images/back_1.jpg')) }}">
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/app/css/services.bundle.min.css') }}">
{% endblock %}

{% block content %}
    <main id="content">
        <section class="spec-holder">
            <div class="inner spec">
                <h1>{{ contentService.mainTitle }}</h1>
                <h2>{{ contentService.subTitleSpecializations }}</h2>
                <p>{{ contentService.textService }}</p>
            </div>
            <div class="spec-icons">
                <ul class="icons-holder">

                    {% for specialization in specializations %}
                        <li>
                            <span class="icon {{ specialization.icon }}"></span>
                            <div class="sptr-small">
                                <span class="line"></span>
                                <span class="line"></span>
                            </div>
                            <p>{{ specialization.title }}</p>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </section>
        <section class="services-holder">
            <h2>{{ contentService.subTitleService }}</h2>
            <div class="services">

                {% for service in services %}
                    <div class="block-holder">
                        <div class="skew">
                            <figure>
                                <img src="{{ asset('bundles/app/images/' ~ service.image) }}" alt="{{ service.title }}">
                            </figure>
                        </div>
                        <div class="inner">
                            <span class="icon {{ service.icon }}"></span>
                            <div class="sptr-small">
                                <span class="line"></span>
                                <span class="line"></span>
                            </div>
                            <span>{{ service.title }}</span>
                            <ul class="list">

                                {% for serviceItem in service.serviceItems %}
                                    <li>{{ serviceItem.title }}</li>
                                {% endfor %}

                            </ul>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </section>
    </main>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bundles/app/js/services.bundle.min.js') }}"></script>
{% endblock %}